// Code generated by protoc-gen-go.
// source: carpcomm/pb/comments.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Comment struct {
	Id               *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId           *string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	ObjectId         *string `protobuf:"bytes,3,opt,name=object_id" json:"object_id,omitempty"`
	Timestamp        *int64  `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Text             *string `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Comment) Reset()         { *this = Comment{} }
func (this *Comment) String() string { return proto.CompactTextString(this) }
func (*Comment) ProtoMessage()       {}

func (this *Comment) GetId() string {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return ""
}

func (this *Comment) GetUserId() string {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return ""
}

func (this *Comment) GetObjectId() string {
	if this != nil && this.ObjectId != nil {
		return *this.ObjectId
	}
	return ""
}

func (this *Comment) GetTimestamp() int64 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func (this *Comment) GetText() string {
	if this != nil && this.Text != nil {
		return *this.Text
	}
	return ""
}

func init() {
}
