// Code generated by protoc-gen-go.
// source: carpcomm/pb/ranking.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ContactCount struct {
	Format           *Contact_Blob_Format `protobuf:"varint,1,opt,name=format,enum=pb.Contact_Blob_Format" json:"format,omitempty"`
	Count            *int32               `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (this *ContactCount) Reset()         { *this = ContactCount{} }
func (this *ContactCount) String() string { return proto.CompactTextString(this) }
func (*ContactCount) ProtoMessage()       {}

func (this *ContactCount) GetFormat() Contact_Blob_Format {
	if this != nil && this.Format != nil {
		return *this.Format
	}
	return 0
}

func (this *ContactCount) GetCount() int32 {
	if this != nil && this.Count != nil {
		return *this.Count
	}
	return 0
}

type Ranking struct {
	UserId           *string         `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Score            *int32          `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	Counts           []*ContactCount `protobuf:"bytes,3,rep,name=counts" json:"counts,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *Ranking) Reset()         { *this = Ranking{} }
func (this *Ranking) String() string { return proto.CompactTextString(this) }
func (*Ranking) ProtoMessage()       {}

func (this *Ranking) GetUserId() string {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return ""
}

func (this *Ranking) GetScore() int32 {
	if this != nil && this.Score != nil {
		return *this.Score
	}
	return 0
}

type RankingList struct {
	Ranking          []*Ranking `protobuf:"bytes,1,rep,name=ranking" json:"ranking,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (this *RankingList) Reset()         { *this = RankingList{} }
func (this *RankingList) String() string { return proto.CompactTextString(this) }
func (*RankingList) ProtoMessage()       {}

func init() {
}
