# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import carpcomm.pb.stream_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='carpcomm/pb/ranking.proto',
  package='pb',
  serialized_pb='\n\x19\x63\x61rpcomm/pb/ranking.proto\x12\x02pb\x1a\x18\x63\x61rpcomm/pb/stream.proto\"F\n\x0c\x43ontactCount\x12\'\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x17.pb.Contact.Blob.Format\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"K\n\x07Ranking\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x12 \n\x06\x63ounts\x18\x03 \x03(\x0b\x32\x10.pb.ContactCount\"+\n\x0bRankingList\x12\x1c\n\x07ranking\x18\x01 \x03(\x0b\x32\x0b.pb.Ranking')




_CONTACTCOUNT = descriptor.Descriptor(
  name='ContactCount',
  full_name='pb.ContactCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='format', full_name='pb.ContactCount.format', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='pb.ContactCount.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=129,
)


_RANKING = descriptor.Descriptor(
  name='Ranking',
  full_name='pb.Ranking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='pb.Ranking.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='score', full_name='pb.Ranking.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='counts', full_name='pb.Ranking.counts', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=131,
  serialized_end=206,
)


_RANKINGLIST = descriptor.Descriptor(
  name='RankingList',
  full_name='pb.RankingList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ranking', full_name='pb.RankingList.ranking', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=208,
  serialized_end=251,
)

_CONTACTCOUNT.fields_by_name['format'].enum_type = carpcomm.pb.stream_pb2._CONTACT_BLOB_FORMAT
_RANKING.fields_by_name['counts'].message_type = _CONTACTCOUNT
_RANKINGLIST.fields_by_name['ranking'].message_type = _RANKING
DESCRIPTOR.message_types_by_name['ContactCount'] = _CONTACTCOUNT
DESCRIPTOR.message_types_by_name['Ranking'] = _RANKING
DESCRIPTOR.message_types_by_name['RankingList'] = _RANKINGLIST

class ContactCount(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTACTCOUNT
  
  # @@protoc_insertion_point(class_scope:pb.ContactCount)

class Ranking(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RANKING
  
  # @@protoc_insertion_point(class_scope:pb.Ranking)

class RankingList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RANKINGLIST
  
  # @@protoc_insertion_point(class_scope:pb.RankingList)

# @@protoc_insertion_point(module_scope)
