// Code generated by protoc-gen-go.
// source: carpcomm/pb/satellite.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Channel_Modulation int32

const (
	Channel_CW       Channel_Modulation = 0
	Channel_BFSK     Channel_Modulation = 1
	Channel_BGFSK    Channel_Modulation = 2
	Channel_GMSK     Channel_Modulation = 3
	Channel_AM_BFSK  Channel_Modulation = 4
	Channel_BPSK     Channel_Modulation = 5
	Channel_FM_AFSK  Channel_Modulation = 6
	Channel_FM_ADPSK Channel_Modulation = 7
	Channel_WIFI     Channel_Modulation = 8
	Channel_LSB_BFSK Channel_Modulation = 9
	Channel_FM_GMSK  Channel_Modulation = 10
	Channel_FM_CW    Channel_Modulation = 11
	Channel_FM_MSK   Channel_Modulation = 12
)

var Channel_Modulation_name = map[int32]string{
	0:  "CW",
	1:  "BFSK",
	2:  "BGFSK",
	3:  "GMSK",
	4:  "AM_BFSK",
	5:  "BPSK",
	6:  "FM_AFSK",
	7:  "FM_ADPSK",
	8:  "WIFI",
	9:  "LSB_BFSK",
	10: "FM_GMSK",
	11: "FM_CW",
	12: "FM_MSK",
}
var Channel_Modulation_value = map[string]int32{
	"CW":       0,
	"BFSK":     1,
	"BGFSK":    2,
	"GMSK":     3,
	"AM_BFSK":  4,
	"BPSK":     5,
	"FM_AFSK":  6,
	"FM_ADPSK": 7,
	"WIFI":     8,
	"LSB_BFSK": 9,
	"FM_GMSK":  10,
	"FM_CW":    11,
	"FM_MSK":   12,
}

func (x Channel_Modulation) Enum() *Channel_Modulation {
	p := new(Channel_Modulation)
	*p = x
	return p
}
func (x Channel_Modulation) String() string {
	return proto.EnumName(Channel_Modulation_name, int32(x))
}
func (x Channel_Modulation) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Channel_Modulation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Channel_Modulation_value, data, "Channel_Modulation")
	if err != nil {
		return err
	}
	*x = Channel_Modulation(value)
	return nil
}

type Channel_DopplerStrategy int32

const (
	Channel_CONSTANT_BURST   Channel_DopplerStrategy = 0
	Channel_HRBE_LINEAR      Channel_DopplerStrategy = 1
	Channel_DISABLED         Channel_DopplerStrategy = 2
	Channel_SNAPS_FCD_OFFSET Channel_DopplerStrategy = 3
)

var Channel_DopplerStrategy_name = map[int32]string{
	0: "CONSTANT_BURST",
	1: "HRBE_LINEAR",
	2: "DISABLED",
	3: "SNAPS_FCD_OFFSET",
}
var Channel_DopplerStrategy_value = map[string]int32{
	"CONSTANT_BURST":   0,
	"HRBE_LINEAR":      1,
	"DISABLED":         2,
	"SNAPS_FCD_OFFSET": 3,
}

func (x Channel_DopplerStrategy) Enum() *Channel_DopplerStrategy {
	p := new(Channel_DopplerStrategy)
	*p = x
	return p
}
func (x Channel_DopplerStrategy) String() string {
	return proto.EnumName(Channel_DopplerStrategy_name, int32(x))
}
func (x Channel_DopplerStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Channel_DopplerStrategy) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Channel_DopplerStrategy_value, data, "Channel_DopplerStrategy")
	if err != nil {
		return err
	}
	*x = Channel_DopplerStrategy(value)
	return nil
}

type Photo struct {
	Url                 *string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	LargeUrl            *string `protobuf:"bytes,2,opt,name=large_url" json:"large_url,omitempty"`
	ThumbnailUrl        *string `protobuf:"bytes,6,opt,name=thumbnail_url" json:"thumbnail_url,omitempty"`
	Attribution         *string `protobuf:"bytes,5,opt,name=attribution" json:"attribution,omitempty"`
	InternalOriginalUrl *string `protobuf:"bytes,3,opt,name=internal_original_url" json:"internal_original_url,omitempty"`
	InternalPermissions *string `protobuf:"bytes,4,opt,name=internal_permissions" json:"internal_permissions,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (this *Photo) Reset()         { *this = Photo{} }
func (this *Photo) String() string { return proto.CompactTextString(this) }
func (*Photo) ProtoMessage()       {}

func (this *Photo) GetUrl() string {
	if this != nil && this.Url != nil {
		return *this.Url
	}
	return ""
}

func (this *Photo) GetLargeUrl() string {
	if this != nil && this.LargeUrl != nil {
		return *this.LargeUrl
	}
	return ""
}

func (this *Photo) GetThumbnailUrl() string {
	if this != nil && this.ThumbnailUrl != nil {
		return *this.ThumbnailUrl
	}
	return ""
}

func (this *Photo) GetAttribution() string {
	if this != nil && this.Attribution != nil {
		return *this.Attribution
	}
	return ""
}

func (this *Photo) GetInternalOriginalUrl() string {
	if this != nil && this.InternalOriginalUrl != nil {
		return *this.InternalOriginalUrl
	}
	return ""
}

func (this *Photo) GetInternalPermissions() string {
	if this != nil && this.InternalPermissions != nil {
		return *this.InternalPermissions
	}
	return ""
}

type CWParams struct {
	DotDurationS     *float64 `protobuf:"fixed64,1,opt,name=dot_duration_s" json:"dot_duration_s,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *CWParams) Reset()         { *this = CWParams{} }
func (this *CWParams) String() string { return proto.CompactTextString(this) }
func (*CWParams) ProtoMessage()       {}

func (this *CWParams) GetDotDurationS() float64 {
	if this != nil && this.DotDurationS != nil {
		return *this.DotDurationS
	}
	return 0
}

type Channel struct {
	FrequencyHz        *float64                 `protobuf:"fixed64,1,opt,name=frequency_hz" json:"frequency_hz,omitempty"`
	Uplink             *bool                    `protobuf:"varint,2,opt,name=uplink" json:"uplink,omitempty"`
	Downlink           *bool                    `protobuf:"varint,3,opt,name=downlink" json:"downlink,omitempty"`
	TransmitPowerWatts *float64                 `protobuf:"fixed64,4,opt,name=transmit_power_watts" json:"transmit_power_watts,omitempty"`
	Modulation         *Channel_Modulation      `protobuf:"varint,5,opt,name=modulation,enum=pb.Channel_Modulation" json:"modulation,omitempty"`
	Baud               *float64                 `protobuf:"fixed64,6,opt,name=baud" json:"baud,omitempty"`
	CwParams           *CWParams                `protobuf:"bytes,9,opt,name=cw_params" json:"cw_params,omitempty"`
	Notes              *string                  `protobuf:"bytes,7,opt,name=notes" json:"notes,omitempty"`
	DocumentationUrl   *string                  `protobuf:"bytes,8,opt,name=documentation_url" json:"documentation_url,omitempty"`
	DopplerStrategy    *Channel_DopplerStrategy `protobuf:"varint,10,opt,name=doppler_strategy,enum=pb.Channel_DopplerStrategy" json:"doppler_strategy,omitempty"`
	XXX_unrecognized   []byte                   `json:"-"`
}

func (this *Channel) Reset()         { *this = Channel{} }
func (this *Channel) String() string { return proto.CompactTextString(this) }
func (*Channel) ProtoMessage()       {}

func (this *Channel) GetFrequencyHz() float64 {
	if this != nil && this.FrequencyHz != nil {
		return *this.FrequencyHz
	}
	return 0
}

func (this *Channel) GetUplink() bool {
	if this != nil && this.Uplink != nil {
		return *this.Uplink
	}
	return false
}

func (this *Channel) GetDownlink() bool {
	if this != nil && this.Downlink != nil {
		return *this.Downlink
	}
	return false
}

func (this *Channel) GetTransmitPowerWatts() float64 {
	if this != nil && this.TransmitPowerWatts != nil {
		return *this.TransmitPowerWatts
	}
	return 0
}

func (this *Channel) GetModulation() Channel_Modulation {
	if this != nil && this.Modulation != nil {
		return *this.Modulation
	}
	return 0
}

func (this *Channel) GetBaud() float64 {
	if this != nil && this.Baud != nil {
		return *this.Baud
	}
	return 0
}

func (this *Channel) GetCwParams() *CWParams {
	if this != nil {
		return this.CwParams
	}
	return nil
}

func (this *Channel) GetNotes() string {
	if this != nil && this.Notes != nil {
		return *this.Notes
	}
	return ""
}

func (this *Channel) GetDocumentationUrl() string {
	if this != nil && this.DocumentationUrl != nil {
		return *this.DocumentationUrl
	}
	return ""
}

func (this *Channel) GetDopplerStrategy() Channel_DopplerStrategy {
	if this != nil && this.DopplerStrategy != nil {
		return *this.DopplerStrategy
	}
	return 0
}

type Satellite struct {
	Id                  *string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                []*TextWithLang  `protobuf:"bytes,2,rep,name=name" json:"name,omitempty"`
	Website             *string          `protobuf:"bytes,3,opt,name=website" json:"website,omitempty"`
	WikipediaUrl        *string          `protobuf:"bytes,14,opt,name=wikipedia_url" json:"wikipedia_url,omitempty"`
	Callsign            *string          `protobuf:"bytes,4,opt,name=callsign" json:"callsign,omitempty"`
	CountryCode         *string          `protobuf:"bytes,8,opt,name=country_code" json:"country_code,omitempty"`
	Organization        []string         `protobuf:"bytes,15,rep,name=organization" json:"organization,omitempty"`
	Description         []*TextWithLang  `protobuf:"bytes,16,rep,name=description" json:"description,omitempty"`
	LaunchTimestamp     *int64           `protobuf:"varint,9,opt,name=launch_timestamp" json:"launch_timestamp,omitempty"`
	ExpectedLaunchTime  *string          `protobuf:"bytes,12,opt,name=expected_launch_time" json:"expected_launch_time,omitempty"`
	OscarId             *string          `protobuf:"bytes,10,opt,name=oscar_id" json:"oscar_id,omitempty"`
	Photo               []*Photo         `protobuf:"bytes,13,rep,name=photo" json:"photo,omitempty"`
	Tle                 *string          `protobuf:"bytes,5,opt,name=tle" json:"tle,omitempty"`
	CelestrakTleLabel   *string          `protobuf:"bytes,6,opt,name=celestrak_tle_label" json:"celestrak_tle_label,omitempty"`
	DisableTracking     *bool            `protobuf:"varint,17,opt,name=disable_tracking" json:"disable_tracking,omitempty"`
	Channels            []*Channel       `protobuf:"bytes,7,rep,name=channels" json:"channels,omitempty"`
	Schema              *TelemetrySchema `protobuf:"bytes,11,opt,name=schema" json:"schema,omitempty"`
	AuthorizedStationId []string         `protobuf:"bytes,18,rep,name=authorized_station_id" json:"authorized_station_id,omitempty"`
	XXX_unrecognized    []byte           `json:"-"`
}

func (this *Satellite) Reset()         { *this = Satellite{} }
func (this *Satellite) String() string { return proto.CompactTextString(this) }
func (*Satellite) ProtoMessage()       {}

func (this *Satellite) GetId() string {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return ""
}

func (this *Satellite) GetWebsite() string {
	if this != nil && this.Website != nil {
		return *this.Website
	}
	return ""
}

func (this *Satellite) GetWikipediaUrl() string {
	if this != nil && this.WikipediaUrl != nil {
		return *this.WikipediaUrl
	}
	return ""
}

func (this *Satellite) GetCallsign() string {
	if this != nil && this.Callsign != nil {
		return *this.Callsign
	}
	return ""
}

func (this *Satellite) GetCountryCode() string {
	if this != nil && this.CountryCode != nil {
		return *this.CountryCode
	}
	return ""
}

func (this *Satellite) GetLaunchTimestamp() int64 {
	if this != nil && this.LaunchTimestamp != nil {
		return *this.LaunchTimestamp
	}
	return 0
}

func (this *Satellite) GetExpectedLaunchTime() string {
	if this != nil && this.ExpectedLaunchTime != nil {
		return *this.ExpectedLaunchTime
	}
	return ""
}

func (this *Satellite) GetOscarId() string {
	if this != nil && this.OscarId != nil {
		return *this.OscarId
	}
	return ""
}

func (this *Satellite) GetTle() string {
	if this != nil && this.Tle != nil {
		return *this.Tle
	}
	return ""
}

func (this *Satellite) GetCelestrakTleLabel() string {
	if this != nil && this.CelestrakTleLabel != nil {
		return *this.CelestrakTleLabel
	}
	return ""
}

func (this *Satellite) GetDisableTracking() bool {
	if this != nil && this.DisableTracking != nil {
		return *this.DisableTracking
	}
	return false
}

func (this *Satellite) GetSchema() *TelemetrySchema {
	if this != nil {
		return this.Schema
	}
	return nil
}

type SatelliteList struct {
	Satellite        []*Satellite `protobuf:"bytes,1,rep,name=satellite" json:"satellite,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *SatelliteList) Reset()         { *this = SatelliteList{} }
func (this *SatelliteList) String() string { return proto.CompactTextString(this) }
func (*SatelliteList) ProtoMessage()       {}

func init() {
	proto.RegisterEnum("pb.Channel_Modulation", Channel_Modulation_name, Channel_Modulation_value)
	proto.RegisterEnum("pb.Channel_DopplerStrategy", Channel_DopplerStrategy_name, Channel_DopplerStrategy_value)
}
