# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='carpcomm/pb/station.proto',
  package='pb',
  serialized_pb='\n\x19\x63\x61rpcomm/pb/station.proto\x12\x02pb\"\x84\x01\n\nAzElLimits\x12\x1b\n\x13min_azimuth_degrees\x18\x01 \x01(\x01\x12\x1b\n\x13max_azimuth_degrees\x18\x02 \x01(\x01\x12\x1d\n\x15min_elevation_degrees\x18\x03 \x01(\x01\x12\x1d\n\x15max_elevation_degrees\x18\x04 \x01(\x01\"\xdc\x02\n\x0c\x43\x61pabilities\x12\"\n\nvhf_limits\x18\n \x01(\x0b\x32\x0e.pb.AzElLimits\x12\"\n\nuhf_limits\x18\x0b \x01(\x0b\x32\x0e.pb.AzElLimits\x12\x14\n\x0chas_receiver\x18\x01 \x01(\x08\x12!\n\x19min_receiver_frequency_hz\x18\x02 \x01(\x01\x12!\n\x19max_receiver_frequency_hz\x18\x03 \x01(\x01\x12\x1d\n\x15receiver_bandwidth_hz\x18\x04 \x01(\x01\x12\x11\n\thas_motor\x18\x05 \x01(\x08\x12\x1b\n\x13min_azimuth_degrees\x18\x06 \x01(\x01\x12\x1b\n\x13max_azimuth_degrees\x18\x07 \x01(\x01\x12\x1d\n\x15min_elevation_degrees\x18\x08 \x01(\x01\x12\x1d\n\x15max_elevation_degrees\x18\t \x01(\x01\"\xfb\x01\n\x07Station\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\t\x12\x0e\n\x06userid\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0b\n\x03lat\x18\x05 \x01(\x01\x12\x0b\n\x03lng\x18\x06 \x01(\x01\x12\x11\n\televation\x18\x07 \x01(\x01\x12\x0f\n\x07\x63reated\x18\x08 \x01(\x03\x12\x14\n\x0clast_connect\x18\t \x01(\x03\x12\x19\n\x11scheduler_enabled\x18\r \x01(\x08\x12\x10\n\x08locality\x18\n \x01(\t\x12\r\n\x05notes\x18\x0b \x01(\t\x12&\n\x0c\x63\x61pabilities\x18\x0c \x01(\x0b\x32\x10.pb.Capabilities')




_AZELLIMITS = descriptor.Descriptor(
  name='AzElLimits',
  full_name='pb.AzElLimits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='min_azimuth_degrees', full_name='pb.AzElLimits.min_azimuth_degrees', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_azimuth_degrees', full_name='pb.AzElLimits.max_azimuth_degrees', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min_elevation_degrees', full_name='pb.AzElLimits.min_elevation_degrees', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_elevation_degrees', full_name='pb.AzElLimits.max_elevation_degrees', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=166,
)


_CAPABILITIES = descriptor.Descriptor(
  name='Capabilities',
  full_name='pb.Capabilities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='vhf_limits', full_name='pb.Capabilities.vhf_limits', index=0,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uhf_limits', full_name='pb.Capabilities.uhf_limits', index=1,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='has_receiver', full_name='pb.Capabilities.has_receiver', index=2,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min_receiver_frequency_hz', full_name='pb.Capabilities.min_receiver_frequency_hz', index=3,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_receiver_frequency_hz', full_name='pb.Capabilities.max_receiver_frequency_hz', index=4,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='receiver_bandwidth_hz', full_name='pb.Capabilities.receiver_bandwidth_hz', index=5,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='has_motor', full_name='pb.Capabilities.has_motor', index=6,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min_azimuth_degrees', full_name='pb.Capabilities.min_azimuth_degrees', index=7,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_azimuth_degrees', full_name='pb.Capabilities.max_azimuth_degrees', index=8,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min_elevation_degrees', full_name='pb.Capabilities.min_elevation_degrees', index=9,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_elevation_degrees', full_name='pb.Capabilities.max_elevation_degrees', index=10,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=169,
  serialized_end=517,
)


_STATION = descriptor.Descriptor(
  name='Station',
  full_name='pb.Station',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='pb.Station.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='secret', full_name='pb.Station.secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userid', full_name='pb.Station.userid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='pb.Station.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lat', full_name='pb.Station.lat', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lng', full_name='pb.Station.lng', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='elevation', full_name='pb.Station.elevation', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='created', full_name='pb.Station.created', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='last_connect', full_name='pb.Station.last_connect', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='scheduler_enabled', full_name='pb.Station.scheduler_enabled', index=9,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='locality', full_name='pb.Station.locality', index=10,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='notes', full_name='pb.Station.notes', index=11,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='capabilities', full_name='pb.Station.capabilities', index=12,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=520,
  serialized_end=771,
)

_CAPABILITIES.fields_by_name['vhf_limits'].message_type = _AZELLIMITS
_CAPABILITIES.fields_by_name['uhf_limits'].message_type = _AZELLIMITS
_STATION.fields_by_name['capabilities'].message_type = _CAPABILITIES
DESCRIPTOR.message_types_by_name['AzElLimits'] = _AZELLIMITS
DESCRIPTOR.message_types_by_name['Capabilities'] = _CAPABILITIES
DESCRIPTOR.message_types_by_name['Station'] = _STATION

class AzElLimits(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AZELLIMITS
  
  # @@protoc_insertion_point(class_scope:pb.AzElLimits)

class Capabilities(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAPABILITIES
  
  # @@protoc_insertion_point(class_scope:pb.Capabilities)

class Station(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATION
  
  # @@protoc_insertion_point(class_scope:pb.Station)

# @@protoc_insertion_point(module_scope)
