// Code generated by protoc-gen-go.
// source: carpcomm/pb/station.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AzElLimits struct {
	MinAzimuthDegrees   *float64 `protobuf:"fixed64,1,opt,name=min_azimuth_degrees" json:"min_azimuth_degrees,omitempty"`
	MaxAzimuthDegrees   *float64 `protobuf:"fixed64,2,opt,name=max_azimuth_degrees" json:"max_azimuth_degrees,omitempty"`
	MinElevationDegrees *float64 `protobuf:"fixed64,3,opt,name=min_elevation_degrees" json:"min_elevation_degrees,omitempty"`
	MaxElevationDegrees *float64 `protobuf:"fixed64,4,opt,name=max_elevation_degrees" json:"max_elevation_degrees,omitempty"`
	XXX_unrecognized    []byte   `json:"-"`
}

func (this *AzElLimits) Reset()         { *this = AzElLimits{} }
func (this *AzElLimits) String() string { return proto.CompactTextString(this) }
func (*AzElLimits) ProtoMessage()       {}

func (this *AzElLimits) GetMinAzimuthDegrees() float64 {
	if this != nil && this.MinAzimuthDegrees != nil {
		return *this.MinAzimuthDegrees
	}
	return 0
}

func (this *AzElLimits) GetMaxAzimuthDegrees() float64 {
	if this != nil && this.MaxAzimuthDegrees != nil {
		return *this.MaxAzimuthDegrees
	}
	return 0
}

func (this *AzElLimits) GetMinElevationDegrees() float64 {
	if this != nil && this.MinElevationDegrees != nil {
		return *this.MinElevationDegrees
	}
	return 0
}

func (this *AzElLimits) GetMaxElevationDegrees() float64 {
	if this != nil && this.MaxElevationDegrees != nil {
		return *this.MaxElevationDegrees
	}
	return 0
}

type Capabilities struct {
	VhfLimits              *AzElLimits `protobuf:"bytes,10,opt,name=vhf_limits" json:"vhf_limits,omitempty"`
	UhfLimits              *AzElLimits `protobuf:"bytes,11,opt,name=uhf_limits" json:"uhf_limits,omitempty"`
	HasReceiver            *bool       `protobuf:"varint,1,opt,name=has_receiver" json:"has_receiver,omitempty"`
	MinReceiverFrequencyHz *float64    `protobuf:"fixed64,2,opt,name=min_receiver_frequency_hz" json:"min_receiver_frequency_hz,omitempty"`
	MaxReceiverFrequencyHz *float64    `protobuf:"fixed64,3,opt,name=max_receiver_frequency_hz" json:"max_receiver_frequency_hz,omitempty"`
	ReceiverBandwidthHz    *float64    `protobuf:"fixed64,4,opt,name=receiver_bandwidth_hz" json:"receiver_bandwidth_hz,omitempty"`
	HasMotor               *bool       `protobuf:"varint,5,opt,name=has_motor" json:"has_motor,omitempty"`
	MinAzimuthDegrees      *float64    `protobuf:"fixed64,6,opt,name=min_azimuth_degrees" json:"min_azimuth_degrees,omitempty"`
	MaxAzimuthDegrees      *float64    `protobuf:"fixed64,7,opt,name=max_azimuth_degrees" json:"max_azimuth_degrees,omitempty"`
	MinElevationDegrees    *float64    `protobuf:"fixed64,8,opt,name=min_elevation_degrees" json:"min_elevation_degrees,omitempty"`
	MaxElevationDegrees    *float64    `protobuf:"fixed64,9,opt,name=max_elevation_degrees" json:"max_elevation_degrees,omitempty"`
	XXX_unrecognized       []byte      `json:"-"`
}

func (this *Capabilities) Reset()         { *this = Capabilities{} }
func (this *Capabilities) String() string { return proto.CompactTextString(this) }
func (*Capabilities) ProtoMessage()       {}

func (this *Capabilities) GetVhfLimits() *AzElLimits {
	if this != nil {
		return this.VhfLimits
	}
	return nil
}

func (this *Capabilities) GetUhfLimits() *AzElLimits {
	if this != nil {
		return this.UhfLimits
	}
	return nil
}

func (this *Capabilities) GetHasReceiver() bool {
	if this != nil && this.HasReceiver != nil {
		return *this.HasReceiver
	}
	return false
}

func (this *Capabilities) GetMinReceiverFrequencyHz() float64 {
	if this != nil && this.MinReceiverFrequencyHz != nil {
		return *this.MinReceiverFrequencyHz
	}
	return 0
}

func (this *Capabilities) GetMaxReceiverFrequencyHz() float64 {
	if this != nil && this.MaxReceiverFrequencyHz != nil {
		return *this.MaxReceiverFrequencyHz
	}
	return 0
}

func (this *Capabilities) GetReceiverBandwidthHz() float64 {
	if this != nil && this.ReceiverBandwidthHz != nil {
		return *this.ReceiverBandwidthHz
	}
	return 0
}

func (this *Capabilities) GetHasMotor() bool {
	if this != nil && this.HasMotor != nil {
		return *this.HasMotor
	}
	return false
}

func (this *Capabilities) GetMinAzimuthDegrees() float64 {
	if this != nil && this.MinAzimuthDegrees != nil {
		return *this.MinAzimuthDegrees
	}
	return 0
}

func (this *Capabilities) GetMaxAzimuthDegrees() float64 {
	if this != nil && this.MaxAzimuthDegrees != nil {
		return *this.MaxAzimuthDegrees
	}
	return 0
}

func (this *Capabilities) GetMinElevationDegrees() float64 {
	if this != nil && this.MinElevationDegrees != nil {
		return *this.MinElevationDegrees
	}
	return 0
}

func (this *Capabilities) GetMaxElevationDegrees() float64 {
	if this != nil && this.MaxElevationDegrees != nil {
		return *this.MaxElevationDegrees
	}
	return 0
}

type Station struct {
	Id               *string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Secret           *string       `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	Userid           *string       `protobuf:"bytes,3,opt,name=userid" json:"userid,omitempty"`
	Name             *string       `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Lat              *float64      `protobuf:"fixed64,5,opt,name=lat" json:"lat,omitempty"`
	Lng              *float64      `protobuf:"fixed64,6,opt,name=lng" json:"lng,omitempty"`
	Elevation        *float64      `protobuf:"fixed64,7,opt,name=elevation" json:"elevation,omitempty"`
	Created          *int64        `protobuf:"varint,8,opt,name=created" json:"created,omitempty"`
	LastConnect      *int64        `protobuf:"varint,9,opt,name=last_connect" json:"last_connect,omitempty"`
	SchedulerEnabled *bool         `protobuf:"varint,13,opt,name=scheduler_enabled" json:"scheduler_enabled,omitempty"`
	Locality         *string       `protobuf:"bytes,10,opt,name=locality" json:"locality,omitempty"`
	Notes            *string       `protobuf:"bytes,11,opt,name=notes" json:"notes,omitempty"`
	Capabilities     *Capabilities `protobuf:"bytes,12,opt,name=capabilities" json:"capabilities,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *Station) Reset()         { *this = Station{} }
func (this *Station) String() string { return proto.CompactTextString(this) }
func (*Station) ProtoMessage()       {}

func (this *Station) GetId() string {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return ""
}

func (this *Station) GetSecret() string {
	if this != nil && this.Secret != nil {
		return *this.Secret
	}
	return ""
}

func (this *Station) GetUserid() string {
	if this != nil && this.Userid != nil {
		return *this.Userid
	}
	return ""
}

func (this *Station) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Station) GetLat() float64 {
	if this != nil && this.Lat != nil {
		return *this.Lat
	}
	return 0
}

func (this *Station) GetLng() float64 {
	if this != nil && this.Lng != nil {
		return *this.Lng
	}
	return 0
}

func (this *Station) GetElevation() float64 {
	if this != nil && this.Elevation != nil {
		return *this.Elevation
	}
	return 0
}

func (this *Station) GetCreated() int64 {
	if this != nil && this.Created != nil {
		return *this.Created
	}
	return 0
}

func (this *Station) GetLastConnect() int64 {
	if this != nil && this.LastConnect != nil {
		return *this.LastConnect
	}
	return 0
}

func (this *Station) GetSchedulerEnabled() bool {
	if this != nil && this.SchedulerEnabled != nil {
		return *this.SchedulerEnabled
	}
	return false
}

func (this *Station) GetLocality() string {
	if this != nil && this.Locality != nil {
		return *this.Locality
	}
	return ""
}

func (this *Station) GetNotes() string {
	if this != nil && this.Notes != nil {
		return *this.Notes
	}
	return ""
}

func (this *Station) GetCapabilities() *Capabilities {
	if this != nil {
		return this.Capabilities
	}
	return nil
}

func init() {
}
