// Code generated by protoc-gen-go.
// source: carpcomm/pb/stream.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type IQParams_Type int32

const (
	IQParams_UINT8   IQParams_Type = 1
	IQParams_SINT16  IQParams_Type = 2
	IQParams_FLOAT32 IQParams_Type = 3
)

var IQParams_Type_name = map[int32]string{
	1: "UINT8",
	2: "SINT16",
	3: "FLOAT32",
}
var IQParams_Type_value = map[string]int32{
	"UINT8":   1,
	"SINT16":  2,
	"FLOAT32": 3,
}

func (x IQParams_Type) Enum() *IQParams_Type {
	p := new(IQParams_Type)
	*p = x
	return p
}
func (x IQParams_Type) String() string {
	return proto.EnumName(IQParams_Type_name, int32(x))
}
func (x IQParams_Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *IQParams_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(IQParams_Type_value, data, "IQParams_Type")
	if err != nil {
		return err
	}
	*x = IQParams_Type(value)
	return nil
}

type Contact_Blob_Format int32

const (
	Contact_Blob_IQ       Contact_Blob_Format = 1
	Contact_Blob_MORSE    Contact_Blob_Format = 2
	Contact_Blob_FRAME    Contact_Blob_Format = 3
	Contact_Blob_DATUM    Contact_Blob_Format = 4
	Contact_Blob_FREEFORM Contact_Blob_Format = 5
)

var Contact_Blob_Format_name = map[int32]string{
	1: "IQ",
	2: "MORSE",
	3: "FRAME",
	4: "DATUM",
	5: "FREEFORM",
}
var Contact_Blob_Format_value = map[string]int32{
	"IQ":       1,
	"MORSE":    2,
	"FRAME":    3,
	"DATUM":    4,
	"FREEFORM": 5,
}

func (x Contact_Blob_Format) Enum() *Contact_Blob_Format {
	p := new(Contact_Blob_Format)
	*p = x
	return p
}
func (x Contact_Blob_Format) String() string {
	return proto.EnumName(Contact_Blob_Format_name, int32(x))
}
func (x Contact_Blob_Format) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Contact_Blob_Format) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Contact_Blob_Format_value, data, "Contact_Blob_Format")
	if err != nil {
		return err
	}
	*x = Contact_Blob_Format(value)
	return nil
}

type IQParams struct {
	SampleRate       *int32         `protobuf:"varint,1,opt,name=sample_rate" json:"sample_rate,omitempty"`
	Type             *IQParams_Type `protobuf:"varint,2,opt,name=type,enum=pb.IQParams_Type" json:"type,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (this *IQParams) Reset()         { *this = IQParams{} }
func (this *IQParams) String() string { return proto.CompactTextString(this) }
func (*IQParams) ProtoMessage()       {}

func (this *IQParams) GetSampleRate() int32 {
	if this != nil && this.SampleRate != nil {
		return *this.SampleRate
	}
	return 0
}

func (this *IQParams) GetType() IQParams_Type {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

type Contact struct {
	Id               *string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	SatelliteId      *string         `protobuf:"bytes,9,opt,name=satellite_id" json:"satellite_id,omitempty"`
	StartTimestamp   *int64          `protobuf:"varint,6,opt,name=start_timestamp" json:"start_timestamp,omitempty"`
	EndTimestamp     *int64          `protobuf:"varint,8,opt,name=end_timestamp" json:"end_timestamp,omitempty"`
	Blob             []*Contact_Blob `protobuf:"bytes,10,rep,name=blob" json:"blob,omitempty"`
	StationId        *string         `protobuf:"bytes,2,opt,name=station_id" json:"station_id,omitempty"`
	UserId           *string         `protobuf:"bytes,7,opt,name=user_id" json:"user_id,omitempty"`
	Lat              *float64        `protobuf:"fixed64,3,opt,name=lat" json:"lat,omitempty"`
	Lng              *float64        `protobuf:"fixed64,4,opt,name=lng" json:"lng,omitempty"`
	Elevation        *float64        `protobuf:"fixed64,5,opt,name=elevation" json:"elevation,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *Contact) Reset()         { *this = Contact{} }
func (this *Contact) String() string { return proto.CompactTextString(this) }
func (*Contact) ProtoMessage()       {}

func (this *Contact) GetId() string {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return ""
}

func (this *Contact) GetSatelliteId() string {
	if this != nil && this.SatelliteId != nil {
		return *this.SatelliteId
	}
	return ""
}

func (this *Contact) GetStartTimestamp() int64 {
	if this != nil && this.StartTimestamp != nil {
		return *this.StartTimestamp
	}
	return 0
}

func (this *Contact) GetEndTimestamp() int64 {
	if this != nil && this.EndTimestamp != nil {
		return *this.EndTimestamp
	}
	return 0
}

func (this *Contact) GetStationId() string {
	if this != nil && this.StationId != nil {
		return *this.StationId
	}
	return ""
}

func (this *Contact) GetUserId() string {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return ""
}

func (this *Contact) GetLat() float64 {
	if this != nil && this.Lat != nil {
		return *this.Lat
	}
	return 0
}

func (this *Contact) GetLng() float64 {
	if this != nil && this.Lng != nil {
		return *this.Lng
	}
	return 0
}

func (this *Contact) GetElevation() float64 {
	if this != nil && this.Elevation != nil {
		return *this.Elevation
	}
	return 0
}

type Contact_Blob struct {
	Format           *Contact_Blob_Format `protobuf:"varint,2,opt,name=format,enum=pb.Contact_Blob_Format" json:"format,omitempty"`
	Path             *string              `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	InlineData       []byte               `protobuf:"bytes,3,opt,name=inline_data" json:"inline_data,omitempty"`
	Datum            *TelemetryDatum      `protobuf:"bytes,4,opt,name=datum" json:"datum,omitempty"`
	IqParams         *IQParams            `protobuf:"bytes,5,opt,name=iq_params" json:"iq_params,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (this *Contact_Blob) Reset()         { *this = Contact_Blob{} }
func (this *Contact_Blob) String() string { return proto.CompactTextString(this) }
func (*Contact_Blob) ProtoMessage()       {}

func (this *Contact_Blob) GetFormat() Contact_Blob_Format {
	if this != nil && this.Format != nil {
		return *this.Format
	}
	return 0
}

func (this *Contact_Blob) GetPath() string {
	if this != nil && this.Path != nil {
		return *this.Path
	}
	return ""
}

func (this *Contact_Blob) GetInlineData() []byte {
	if this != nil {
		return this.InlineData
	}
	return nil
}

func (this *Contact_Blob) GetDatum() *TelemetryDatum {
	if this != nil {
		return this.Datum
	}
	return nil
}

func (this *Contact_Blob) GetIqParams() *IQParams {
	if this != nil {
		return this.IqParams
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.IQParams_Type", IQParams_Type_name, IQParams_Type_value)
	proto.RegisterEnum("pb.Contact_Blob_Format", Contact_Blob_Format_name, Contact_Blob_Format_value)
}
