# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import carpcomm.pb.text_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='carpcomm/pb/telemetry.proto',
  package='pb',
  serialized_pb='\n\x1b\x63\x61rpcomm/pb/telemetry.proto\x12\x02pb\x1a\x16\x63\x61rpcomm/pb/text.proto\"\x84\x03\n\x14TelemetryDatumSchema\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nsource_key\x18\x07 \x01(\t\x12+\n\x04type\x18\x02 \x01(\x0e\x32\x1d.pb.TelemetryDatumSchema.Type\x12+\n\x04unit\x18\x03 \x01(\x0e\x32\x1d.pb.TelemetryDatumSchema.Unit\x12\x1e\n\x04name\x18\x04 \x03(\x0b\x32\x10.pb.TextWithLang\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x12\x15\n\rdisplay_group\x18\x06 \x01(\x05\"D\n\x04Type\x12\x08\n\x04\x42OOL\x10\x01\x12\n\n\x06\x44OUBLE\x10\x02\x12\x0c\n\x08INTERVAL\x10\x03\x12\t\n\x05INT64\x10\x04\x12\r\n\tTIMESTAMP\x10\x05\"`\n\x04Unit\x12\n\n\x06KELVIN\x10\x01\x12\x08\n\x04VOLT\x10\x02\x12\n\n\x06\x41MPERE\x10\x03\x12\x08\n\x04WATT\x10\x04\x12\t\n\x05HERTZ\x10\x05\x12\x15\n\x11RADIAN_PER_SECOND\x10\x06\x12\n\n\x06SECOND\x10\x07\":\n\x0fTelemetrySchema\x12\'\n\x05\x64\x61tum\x18\x01 \x03(\x0b\x32\x18.pb.TelemetryDatumSchema\"\xa4\x01\n\x0eTelemetryDatum\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07\x62oolean\x18\x03 \x01(\x08\x12\x0e\n\x06\x64ouble\x18\x04 \x01(\x01\x12\x14\n\x0cinterval_min\x18\x05 \x01(\x01\x12\x14\n\x0cinterval_max\x18\x06 \x01(\x01\x12\r\n\x05int64\x18\x07 \x01(\x03\x12\x16\n\x0eunix_timestamp\x18\x08 \x01(\x03')



_TELEMETRYDATUMSCHEMA_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='pb.TelemetryDatumSchema.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='BOOL', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DOUBLE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INTERVAL', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INT64', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TIMESTAMP', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=282,
  serialized_end=350,
)

_TELEMETRYDATUMSCHEMA_UNIT = descriptor.EnumDescriptor(
  name='Unit',
  full_name='pb.TelemetryDatumSchema.Unit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='KELVIN', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VOLT', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AMPERE', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WATT', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HERTZ', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RADIAN_PER_SECOND', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SECOND', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=352,
  serialized_end=448,
)


_TELEMETRYDATUMSCHEMA = descriptor.Descriptor(
  name='TelemetryDatumSchema',
  full_name='pb.TelemetryDatumSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='pb.TelemetryDatumSchema.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source_key', full_name='pb.TelemetryDatumSchema.source_key', index=1,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='pb.TelemetryDatumSchema.type', index=2,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unit', full_name='pb.TelemetryDatumSchema.unit', index=3,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='pb.TelemetryDatumSchema.name', index=4,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='confidence', full_name='pb.TelemetryDatumSchema.confidence', index=5,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='display_group', full_name='pb.TelemetryDatumSchema.display_group', index=6,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TELEMETRYDATUMSCHEMA_TYPE,
    _TELEMETRYDATUMSCHEMA_UNIT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=60,
  serialized_end=448,
)


_TELEMETRYSCHEMA = descriptor.Descriptor(
  name='TelemetrySchema',
  full_name='pb.TelemetrySchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='datum', full_name='pb.TelemetrySchema.datum', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=450,
  serialized_end=508,
)


_TELEMETRYDATUM = descriptor.Descriptor(
  name='TelemetryDatum',
  full_name='pb.TelemetryDatum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='pb.TelemetryDatum.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='pb.TelemetryDatum.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='boolean', full_name='pb.TelemetryDatum.boolean', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='double', full_name='pb.TelemetryDatum.double', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='interval_min', full_name='pb.TelemetryDatum.interval_min', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='interval_max', full_name='pb.TelemetryDatum.interval_max', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int64', full_name='pb.TelemetryDatum.int64', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unix_timestamp', full_name='pb.TelemetryDatum.unix_timestamp', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=511,
  serialized_end=675,
)

_TELEMETRYDATUMSCHEMA.fields_by_name['type'].enum_type = _TELEMETRYDATUMSCHEMA_TYPE
_TELEMETRYDATUMSCHEMA.fields_by_name['unit'].enum_type = _TELEMETRYDATUMSCHEMA_UNIT
_TELEMETRYDATUMSCHEMA.fields_by_name['name'].message_type = carpcomm.pb.text_pb2._TEXTWITHLANG
_TELEMETRYDATUMSCHEMA_TYPE.containing_type = _TELEMETRYDATUMSCHEMA;
_TELEMETRYDATUMSCHEMA_UNIT.containing_type = _TELEMETRYDATUMSCHEMA;
_TELEMETRYSCHEMA.fields_by_name['datum'].message_type = _TELEMETRYDATUMSCHEMA
DESCRIPTOR.message_types_by_name['TelemetryDatumSchema'] = _TELEMETRYDATUMSCHEMA
DESCRIPTOR.message_types_by_name['TelemetrySchema'] = _TELEMETRYSCHEMA
DESCRIPTOR.message_types_by_name['TelemetryDatum'] = _TELEMETRYDATUM

class TelemetryDatumSchema(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TELEMETRYDATUMSCHEMA
  
  # @@protoc_insertion_point(class_scope:pb.TelemetryDatumSchema)

class TelemetrySchema(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TELEMETRYSCHEMA
  
  # @@protoc_insertion_point(class_scope:pb.TelemetrySchema)

class TelemetryDatum(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TELEMETRYDATUM
  
  # @@protoc_insertion_point(class_scope:pb.TelemetryDatum)

# @@protoc_insertion_point(module_scope)
