# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='carpcomm/pb/text.proto',
  package='pb',
  serialized_pb='\n\x16\x63\x61rpcomm/pb/text.proto\x12\x02pb\"*\n\x0cTextWithLang\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t')




_TEXTWITHLANG = descriptor.Descriptor(
  name='TextWithLang',
  full_name='pb.TextWithLang',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='pb.TextWithLang.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lang', full_name='pb.TextWithLang.lang', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['TextWithLang'] = _TEXTWITHLANG

class TextWithLang(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEXTWITHLANG
  
  # @@protoc_insertion_point(class_scope:pb.TextWithLang)

# @@protoc_insertion_point(module_scope)
