// Code generated by protoc-gen-go.
// source: carpcomm/pb/text.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type TextWithLang struct {
	Text             *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Lang             *string `protobuf:"bytes,2,opt,name=lang" json:"lang,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *TextWithLang) Reset()         { *this = TextWithLang{} }
func (this *TextWithLang) String() string { return proto.CompactTextString(this) }
func (*TextWithLang) ProtoMessage()       {}

func (this *TextWithLang) GetText() string {
	if this != nil && this.Text != nil {
		return *this.Text
	}
	return ""
}

func (this *TextWithLang) GetLang() string {
	if this != nil && this.Lang != nil {
		return *this.Lang
	}
	return ""
}

func init() {
}
