// Code generated by protoc-gen-go.
// source: carpcomm/pb/user.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type User struct {
	Id               *string `protobuf:"bytes,8,opt,name=id" json:"id,omitempty"`
	GoogleKey        *string `protobuf:"bytes,1,opt,name=google_key" json:"google_key,omitempty"`
	Created          *int64  `protobuf:"varint,2,opt,name=created" json:"created,omitempty"`
	LastLogin        *int64  `protobuf:"varint,3,opt,name=last_login" json:"last_login,omitempty"`
	Email            *string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	DisplayName      *string `protobuf:"bytes,5,opt,name=display_name" json:"display_name,omitempty"`
	PhotoUrl         *string `protobuf:"bytes,6,opt,name=photo_url" json:"photo_url,omitempty"`
	Authority        *string `protobuf:"bytes,7,opt,name=authority" json:"authority,omitempty"`
	Callsign         *string `protobuf:"bytes,9,opt,name=callsign" json:"callsign,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *User) Reset()         { *this = User{} }
func (this *User) String() string { return proto.CompactTextString(this) }
func (*User) ProtoMessage()       {}

func (this *User) GetId() string {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return ""
}

func (this *User) GetGoogleKey() string {
	if this != nil && this.GoogleKey != nil {
		return *this.GoogleKey
	}
	return ""
}

func (this *User) GetCreated() int64 {
	if this != nil && this.Created != nil {
		return *this.Created
	}
	return 0
}

func (this *User) GetLastLogin() int64 {
	if this != nil && this.LastLogin != nil {
		return *this.LastLogin
	}
	return 0
}

func (this *User) GetEmail() string {
	if this != nil && this.Email != nil {
		return *this.Email
	}
	return ""
}

func (this *User) GetDisplayName() string {
	if this != nil && this.DisplayName != nil {
		return *this.DisplayName
	}
	return ""
}

func (this *User) GetPhotoUrl() string {
	if this != nil && this.PhotoUrl != nil {
		return *this.PhotoUrl
	}
	return ""
}

func (this *User) GetAuthority() string {
	if this != nil && this.Authority != nil {
		return *this.Authority
	}
	return ""
}

func (this *User) GetCallsign() string {
	if this != nil && this.Callsign != nil {
		return *this.Callsign
	}
	return ""
}

func init() {
}
